### ISSUE TITLE
Dropping bad series data? 

### ISSUE THREAD

**Issue by DandyDeveloper** [blind-oracle/cortex-tenant#1]
I have a situation where some Cassandra exporters are outputting bad data for me which I need to resolve. 

In the meantime, as a workaround, I'd like to be able to just drop these series on a certain number of rejections.

Example of what I'm seeing;

```sh
time="2021-05-12T04:51:15Z" level=error msg="proc: src=10.244.3.46:60714 req_id=e67dc8e2-eaf7-48a8-95b9-977b3f3e34a6 HTTP code 400 (user=xyz: sample with repeated timestamp but different value; last value: NaN, incoming value: 0 for series {__name__=\"cassandra_table_readlatency_mean\", app=\"rook-cassandra\", app_kubernetes_io_managed_by=\"rook-cassandra-operator\", app_kubernetes_io_name=\"rook-cassandra\", cassandra_rook_io_cluster=\"rook-cassandra\", keyspace=\"cortex\", kubernetes_namespace=\"rook-cassandra\", kubernetes_pod_name=\"rook-cassandra-aus1-aus1rack1-0\",table=\"chunks_2670\"}\n)"
time="2021-05-12T04:51:15Z" level=error msg="proc: src=10.244.3.46:60714 req_id=562fbe5b-f593-4159-bc3c-155a58f53012 HTTP code 400 (user=xyz: sample with repeated timestamp but different value; last value: NaN, incoming value: 0 for series {__name__=\"cassandra_table_readlatency_mean\", app=\"rook-cassandra\", app_kubernetes_io_managed_by=\"rook-cassandra-operator\", app_kubernetes_io_name=\"rook-cassandra\", cassandra_rook_io_cluster=\"rook-cassandra\", keyspace=\"system\", kubernetes_namespace=\"rook-cassandra\", kubernetes_pod_name=\"rook-cassandra-aus1-aus1rack1-0\",table=\"batches\"}\n)"
```

So in this case, I'm getting a 400, and it looks like these effectively bottleneck the tenant because nothing is being done with this series on rejection. 

Does this have any inherent logic to remove "bad" series or rejected series from Cortex?

**Comment by DandyDeveloper** [comment]
Nevermind, this is Prometheus constantly throwing the bad series in. Worked around it via Prom instead.

**Comment by blind-oracle** [comment]
Well, I can add an option to always reply code 200 to Prometheus regardless of whether Cortex accepted the data or not. But yeah, it's better to handle the bad data at the source.

**Comment by DandyDeveloper** [comment]
@blind-oracle Yeah, ignore this issue. I think it would be a bandaid that would cause more problems then it solves. Sorry to bother you!

**Comment by DandyDeveloper** [comment]
@blind-oracle I've come back to this deciding for me it'd be better to have the option to always 200. 

Right now, through teething issues / bad implementation of some federations (and memory shortage) I'm experiencing a number of pitfalls from WAL buildup due to 500 errors.

I'll maybe make a PR, but it'd be great to have an option to always 200 the docs.

**Comment by blind-oracle** [comment]
Fixed in PR
