### ISSUE TITLE
Propagate metrics metadata to Cortex

### ISSUE THREAD

**Issue by Paszymaja** [blind-oracle/cortex-tenant#10]
Hi, we came across a problem when trying to get information about the [metrics metadata in Cortex.](https://cortexmetrics.io/docs/api/#get-metric-metadata)
Currently, metadata requests from Prometheus are dropped as they don't include timeseries. From line 119 in processor.go
```go
// If there's metadata - just accept the request and drop it
if len(wrReqIn.Metadata) > 0 {
    return
}
```
Could we discuss why this is the case and if is it possible to add functionality to forward metadata to Cortex?
Documentation from Cortex: https://cortexmetrics.io/docs/proposals/support-metadata-api/

Thanks in advance 👍

**Comment by blind-oracle** [comment]
Hi,

There were some problems in earlier versions of Cortex with metadata pushing AFAIR.
Not sure if that's still relevant. I can add a (disabled by default) setting to enable passthrough of it - will that work for you?

**Comment by Paszymaja** [comment]
Yes, if you could I will happily test it.

**Comment by blind-oracle** [comment]
The only thing is how do we determine the tenant to use when sending metadata? As we don't have timeseries in a request we can't rely on labels to do this. I can only think of using a default tenant or some metadata-specific one

**Comment by Paszymaja** [comment]
Sending data to the default tenant would be sufficient for us.

**Comment by blind-oracle** [comment]
I've published a new release, try to see if it fits you

**Comment by Paszymaja** [comment]
@blind-oracle We deployed the new version and everything works as expected.
Thank you very much for changing it so fast!
