### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by till** [blind-oracle/cortex-tenant#12]
Would you be up for publishing a docker image? E.g. using GH packages? I can PR a workflow.

**Comment by till** [comment]
> Sure, no problem if you can prepare it.
> 
> I'm not much into Docker, so can't really check or verify the procedure, but will do my best.

LMK when you had the chance to make a release. And I'll check the docker image.

**Comment by blind-oracle** [comment]
I ran the workflow, it seems to have generated a packege

**Comment by till** [comment]
@blind-oracle great, can you do a v1.6.1 release some time?
