### ISSUE TITLE
Cortex-tenant K8s manifests

### ISSUE THREAD

**Issue by prprasad2020** [blind-oracle/cortex-tenant#15]
@blind-oracle I have created deployment, service and configmap(_configuration file_) manifest to deploy cortex-tenant docker image in a Kubernetes cluster. Is it okay if I push those to this repo ? I can not attach those in this issue.

**Comment by blind-oracle** [comment]
Hi, sure, create a PR.
Maybe put them in `deploy/k8` folder and add some mention to README so that the people can find it :)

**Comment by prprasad2020** [comment]
I have created the files and updated the readme. But seems like I do not have write access to this repo in order to push the changes. @blind-oracle could you be able to fix it ?

**Comment by prprasad2020** [comment]
Hey, Thanks. I created one
