### ISSUE TITLE
Release version 1.7.2

### ISSUE THREAD

**Issue by marcinfigiel** [blind-oracle/cortex-tenant#22]
Hi @blind-oracle,

Could you please merge #24 and tag the 1.7.2 release?

Thanks!

**Comment by marcinfigiel** [comment]
@blind-oracle are there any blockers for this?

**Comment by blind-oracle** [comment]
@marcinfigiel No, sorry, just needed to allocate a few minutes :)

Posted v1.7.3 also with deps update

**Comment by marcinfigiel** [comment]
Thank you! :)
