### ISSUE TITLE
Prefix params doesn't work

### ISSUE THREAD

**Issue by Ronan-WeScale** [blind-oracle/cortex-tenant#37]
I deployed on openshift with the K8S sample config dans run into this error :

`level=fatal msg="Unable to parse config: yaml: unmarshal errors:\n  line 28: field prefix not found in type struct { Label string; LabelRemove bool \"yaml:\\\"label_remove\\\"\"; Header string; Default string; AcceptAll bool \"yaml:\\\"accept_all\\\"\" }"`

When I comment this params that's work, but I need to prefix tenant name

**Comment by Ronan-WeScale** [comment]
I think the latest image isn't up to date

**Comment by Ronan-WeScale** [comment]
![image](https://github.com/blind-oracle/cortex-tenant/assets/121817542/0b982b5a-590c-4ea3-ab30-c28e2b08ffbf)

**Comment by blind-oracle** [comment]
Yeah, `latest` tag is kinda old, please use version for now. I've update the Github Actions to make `latest` to track `master` branch (it's harder to make it track latest release)
