### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by lenglet-k** [blind-oracle/cortex-tenant#51]
Hello,

Can you create a tag 1.11.1 with max_conns_per_host configuration ?

Thanks you

**Comment by blind-oracle** [comment]
Done, sorry for long waiting

**Comment by lenglet-k** [comment]
Hi, thanks you, have you build a docker images ?

**Comment by lenglet-k** [comment]
with the tag v1.12.3 ? see here my issue: https://github.com/blind-oracle/cortex-tenant/issues/58
