### ISSUE TITLE
Security: Do i need to put nginx or anything in front of cortex-tenant?

### ISSUE THREAD

**Issue by venkatamutyala** [blind-oracle/cortex-tenant#63]
I was thinking about deploying cortex-tenant on the public web and just configuring my tenants to send data to it. Beyond being at risk for a bunch of useless metrics data being shipped to me, are there any other risks to be aware of? As far as I can tell this project is a is a write only endpoint so no one should be able to read data that they send to me?

**Comment by blind-oracle** [comment]
Should be safe, but:
* No TLS
* No ingress auth (yet)

Adding simple basic auth should be easy I guess, but since there's no TLS it might be susceptible to sniffing
