### ISSUE TITLE
[chart] Set `autoscaling.minReplica=2` by default

### ISSUE THREAD

**Issue by AndersBennedsgaard** [blind-oracle/cortex-tenant#66]
By default, `autoscaling.enabled=true`, `autoscaling.minReplica=1`, `podDisruptionBudget.enabled=true`, and `podDisruptionBudget.minAvailable=1`. 

This means that since (by default) the HPA allows autoscaling to 1 replica, you might get errors when patching nodes, since `kubectl drain` will try to remove the single Cortex Tenant pod, which the PDB doesn't allow.

The workaround is simple; set `autoscaling.minReplica=2` or disable the PDB.
However, it would be nice if the chart is possible to deploy to a cluster with as few changes as possible, so I would like the chart to have `autoscaling.minReplica=2` by default. What do you think of this?

**Comment by blind-oracle** [comment]
Sorry for late answer.
I have no problems with that, but since I don't use k8s at all, I have no strong opinion. If you want to change that - please make a PR :)
