### ISSUE TITLE
[chart] Add health/readiness probes

### ISSUE THREAD

**Issue by AndersBennedsgaard** [blind-oracle/cortex-tenant#67]
To make sure that the service is ready to receive requests, it would be nice to be able to configure liveness and readiness probes in the Helm chart.

These could (by default) be set up such that the liveness probe checks for TCP liveness by attempting to open a connection to a specified port (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-tcp-liveness-probe) and the readiness probe could check the `/alive` using `httpGet` (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request).

Currently, the workaround is to manually create a post-renderer which attaches the probes, but it could be nice if this was added to the Helm chart

**Comment by ksrt12** [comment]
@AndersBennedsgaard implemented in https://github.com/blind-oracle/cortex-tenant/pull/69 (disabled by default)
