### ISSUE TITLE
Cortex Authentication Enabled

### ISSUE THREAD

**Issue by jnsrikanth** [blind-oracle/cortex-tenant#7]
Hi,

I am using multiple prometheus deployments on multiple Kubernetes (k8s) clusters that use the remote_write HTTP API to push metrics to Cortex deployed in a target/destination k8s cluster. However currently I am using auth_enabled to true and adding basic_auth with username and password to authenticate each prometheus deployment per tenant to authenticate to the remote Cortex using an nginx reverse proxy.

However I am finding this entire setup to be quite cumbersome. So, if I were to use cortex-tenant, can I achieve multi tenancy at a per physical tenant (single prometheus deployed into a tenant k8s cluster) which are each using its own remote_write API to write to Cortex? Is this even possible? Do I still need to enable auth in cortex? (I am using a Helm chart to deploy cortex).

Kindly let me know.

**Comment by jnsrikanth** [comment]
Thanks for the quick response @blind-oracle. So as per the latest cortex release, in order to use multi-tenancy, we need to enable authentication in cortex and then use some kind of basic_auth in prometheus that sends username and password in addition to X-Scope-Orig header via prometheus remote_write to a nginx reverse proxy (placed in front of cortex-distributor etc.) that actually authenticates a Prometheus credentials and then routes to cortex-distributor based on X-Scope-OrigID which leads to a separate TSDB at the Ingesters.

So as per you and per the cortex-tenant that you have, I can get rid of this entire nginx proxy and not send any credentials from prometheus but only send a X-Scope-OrigID header along with a label in order to create separate TSDB for each tenant? Can you point me to a Kubernetes configuration (YAML) if there is any? Thank you once again. And sorry for being so elaborate again.

**Comment by blind-oracle** [comment]
> I can get rid of this entire nginx proxy and not send any credentials from prometheus but only send a X-Scope-OrigID header along with a label in order to create separate

Yes, if you need a global per-prometheus-instance label, you can use `external_labels` like this:
```
external_labels:
  __tenant__: foobar
```
Then it will be added to all Prometheus remote writes. Or you can have different per-job labels if needed.

After that you configure `cortex-tenant` to use this `__tenant__` label and its value will be put into outgoing write request to Cortex into `X-SCope-Org-Id` HTTP header.
