### ISSUE TITLE
cortex-tenant proxy ignores Cortex error codes

### ISSUE THREAD

**Issue by Paszymaja** [blind-oracle/cortex-tenant#8]
Proxy always return 500 error (https://github.com/blind-oracle/cortex-tenant/blob/main/processor.go#L153 ) to Prometheus even then Cortex returns 400.

The problem is with [Line 143](https://github.com/blind-oracle/cortex-tenant/blob/main/processor.go#L143):

```golang
    } else if r.code < 200 || r.code >= 300 {
      errs = me.Append(errs, fmt.Errorf("HTTP code %d (%s)", r.code, string(r.body)))
      p.Errorf("src=%s req_id=%s HTTP code %d (%s)", clientIP, reqID, r.code, string(r.body))
    }
```

Error is added to the collection when Cortex returns non-2xx code, so the code below it basically doesn’t make sense, as the method always returns code 500 in [line 150](https://github.com/blind-oracle/cortex-tenant/blob/main/processor.go#L150).
```golang
	if errs.ErrorOrNil() != nil {
		ctx.Error(errs.Error(), fh.StatusInternalServerError)
		return
	}
```

This also means that flag AcceptAll in [line 154](https://github.com/blind-oracle/cortex-tenant/blob/main/processor.go#L154) doesn't work.

This leads to Prometheus always retry requests even when by default it should not. See:

https://github.com/prometheus/prometheus/blob/fe06f16c116a109330cce0bcb61c2c6728ab7227/storage/remote/client.go#L228 

Prometheus only retries on 5XX errors.

## Problem

When trying to send out-of-order metrics using the proxy Prometheus get stuck in the retry loop so no data is sent. From the proxy, I would expect the same behaviour as the normal Prometheus --> cortex path.

Prometheus:

```
ts=2021-11-09T08:50:06.236Z caller=dedupe.go:112 component=remote level=warn remote_name=cortex_tenant url=http://127.0.0.1:8070/push msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: 1 error occurred:"
ts=2021-11-09T08:51:06.313Z caller=dedupe.go:112 component=remote level=warn remote_name=cortex_tenant url=http://127.0.0.1:8070/push msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: 1 error occurred:"
ts=2021-11-09T08:52:06.321Z caller=dedupe.go:112 component=remote level=warn remote_name=cortex_tenant url=http://127.0.0.1:8070/push msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: 1 error occurred:"
ts=2021-11-09T08:53:06.366Z caller=dedupe.go:112 component=remote level=warn remote_name=cortex_tenant url=http://127.0.0.1:8070/push msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: 1 error occurred:"
ts=2021-11-09T08:54:06.385Z caller=dedupe.go:112 component=remote level=warn remote_name=cortex_tenant url=http://127.0.0.1:8070/push msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: 1 error occurred:"
```

Cortex-proxy:

```
time="2021-11-09T08:55:48Z" level=error msg="proc: src=127.0.0.1:41428 req_id=5fe80dbd-06ec-41a6-987d-f3d0960fcfd5 HTTP code 400 (user=user-default: err: out of order sample. timestamp=2021-11-09T06:41:54.143Z, series= ...
time="2021-11-09T08:55:48Z" level=error msg="proc: src=127.0.0.1:41798 req_id=f2e31318-940c-4bdd-bbff-8434b00da2e6 HTTP code 400 (user=user-default: err: out of order sample. timestamp=2021-11-09T06:41:43.816Z, series= ...
```

Cortex-distributor:

```
level=error ts=2021-11-09T08:55:12.142835681Z caller=push.go:51 org_id=org-id traceID=368b869738f1dffe msg="push error" err="rpc error: code = Code(400) desc = user=user-default: err: out of order sample. timestamp=2021-11-09T06:41:43.816Z, series= ...
level=error ts=2021-11-09T08:55:12.154785238Z caller=push.go:51 org_id=org-id traceID=2a175fef0e882923 msg="push error" err="rpc error: code = Code(400) desc = user=user-default: err: out of order sample. timestamp=2021-11-09T06:42:02.956Z, series= ...
```

**Comment by marcinfigiel** [comment]
Hi @blind-oracle,
I think the base for the fix should be an analysis of what happens with the data in the Prometheus remote-write flow. Looking at the Prometheus _client.go_ [`Store`](https://github.com/prometheus/prometheus/blob/fe06f16c116a109330cce0bcb61c2c6728ab7227/storage/remote/client.go#L191) function we can identify 3 situations in which Prometheus will retry the request:
- a connection/network error,
- 429 response code,
- any 5xx response code.

And the goal should be to make sure not to break the Prometheus and not to lose data.

With that in mind I think your idea of returning the highest response code is good. It should allow Prometheus to retry the request when necessary and to move on with it when needed. It should not get stuck in an infinite retry loop like it does now and it should not lose any data. The worst that could happen is an unnecessary retry sent from the proxy to the Cortex if for example it was already sent before as part of a bigger request coming from Prometheus which caused a 5xx response from any other part. But in this case the retry should return a 400 response (sample out of order) which would still allow Prometheus to move on with its processing.

So if I didn't miss anything the fix should be good and quite simple too.

**Comment by blind-oracle** [comment]
@marcinfigiel Thanks. Well that's kinda strange that they retry on any 5xx error as only 503/504 are inherently recoverable I think. Maybe 500 too but it's too generic. 

But whatever, then let's implement passing highest code from Cortex back and see how it works, will adjust if it breaks something. I'll do a commit today maybe.

**Comment by marcinfigiel** [comment]
Agree, but we must deal with what they've implemented.
Great, thanks! We will test the new version as soon as it's here :)

**Comment by blind-oracle** [comment]
@marcinfigiel @Paszymaja Published a new release, lemme know it it suits your needs.

**Comment by Paszymaja** [comment]
Thanks, we will check it out :)

**Comment by marcinfigiel** [comment]
@blind-oracle we've deployed the new version and so far, so good. Everything works as expected, we haven't noticed any regression and the issue with Prometheus falling into an infinite-retry-loop is gone. 
Thank you so much for fixing it so fast!
